"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
"""


def fibonacci(limit):
    """ There is a faster solution, but I like this one, 
        because it's still fast enough and very easy to understand """
    a,b = 0,1
    
    s = []
    
    while a+b < limit:
        a,b = b, a+b 
        s.append(b)
        
    return sum([i for i in s if i % 2 == 0])


  

print fibonacci(4000000)